FROM golang:1.26-alpine AS builder

WORKDIR /app

RUN apk add --no-cache git

# 依存関係のコピーとダウンロード
COPY go.mod go.sum ./
RUN go mod download

# ソースコードをコピーしてビルド
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o agent ./cmd/agent/main.go

FROM alpine:latest
RUN apk add --no-cache ca-certificates

WORKDIR /app
COPY --from=builder /app/agent .

CMD ["./agent"]